name: volta
description: A new Flutter project.
publish_to:
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc:
  flutter_offline: ^3.0.1
  qr_flutter: ^4.1.0
  flutter_bloc:
  http:
  qr_code_scanner: ^1.0.1
  equatable: ^2.0.5
  animated_text_kit: ^4.2.1
  lottie: ^1.3.0
  fluttertoast: ^8.0.8
  curved_labeled_navigation_bar: ^2.0.2
  flutter_barcode_scanner: ^2.0.0
  flutter_svg: ^2.0.10+1
  simple_circular_progress_bar: ^1.0.2
  flutter_rating_bar: ^4.0.1
  get: ^4.6.6
  line_awesome_flutter: ^3.0.1
  dashed_circular_progress_bar: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/


